version: '2'
services:
###################
##### example minio install
  minio:
    image: minio/minio
    ports:
       - "${MINIO_PORT}:9000"
    volumes:
      - ./minio_storage:/data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET}
    command: minio server /data
####################
##### example container to create a new bucket if doesn't exist
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 20;
      /usr/bin/mc config host add custom_instance ${MINIO_PROTOCOL}://${MINIO_HOST} ${MINIO_KEY} ${MINIO_SECRET};
      /usr/bin/mc rm -r --force custom_instance/${MINIO_BUCKET};
      /usr/bin/mc mb custom_instance/${MINIO_BUCKET};
       /usr/bin/mc policy download custom_instance/${MINIO_BUCKET};
      exit 0;
      "
