version: '2'
services:
  sidecar-backup-mysql:
      image: beeckup/sidecar-backup-mysql:latest
      volumes:
          - ./dumpdb:/go/src/app/dumpdb
      restart: always
      environment:
        - MYSQL_HOST=${MYSQL_HOST}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_SQL_FILENAME=${MYSQL_SQL_FILENAME}
        - SCHEDULE=${SCHEDULE}
        - S3_UPLOAD=${S3_UPLOAD}
        - S3_BUCKET=${S3_BUCKET}
        - S3_KEY=${S3_KEY}
        - S3_SECRET=${S3_SECRET}
        - S3_HOST=${S3_HOST}
        - S3_PROTOCOL=${S3_PROTOCOL}
        - ZIP_FILE=${ZIP_FILE}
        - MYSQL_ALL_DB=${MYSQL_ALL_DB}
        - CLEAN_DAYS=${CLEAN_DAYS}
##################
##### example db
  db:
      image: mysql:5.7.22
      restart: always
      ports:
        - "3306:3306" #only test
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
