version: '2'
services:
##################
##### example db
  db:
      image: mysql:5.7.22
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}