version: '2'
services:
  sidecar-backup-mysql:
      image: nutellinoit/sidecar-backup-mysql:1.0
      volumes:
          - ./dumpdb:/go/src/app/dumpdb
      restart: always
      environment:
        - MYSQL_HOST=db
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=root
        - MYSQL_PASSWORD=123456
        - MYSQL_SQL_FILENAME=nomebackup
        - SCHEDULE=0 * * * * *
  db:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_DATABASE: wordpress
        MYSQL_ROOT_PASSWORD: 123456
